# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '123.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 469)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 341, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.name1.setText("")
        self.name1.setObjectName("name1")
        self.verticalLayout.addWidget(self.name1)
        self.name2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.name2.setText("")
        self.name2.setObjectName("name2")
        self.verticalLayout.addWidget(self.name2)
        self.name3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.name3.setText("")
        self.name3.setObjectName("name3")
        self.verticalLayout.addWidget(self.name3)
        self.name4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.name4.setText("")
        self.name4.setObjectName("name4")
        self.verticalLayout.addWidget(self.name4)
        self.name5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.name5.setText("")
        self.name5.setObjectName("name5")
        self.verticalLayout.addWidget(self.name5)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(360, -10, 121, 461))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.open1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.open1.setObjectName("open1")
        self.verticalLayout_2.addWidget(self.open1)
        self.open2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.open2.setObjectName("open2")
        self.verticalLayout_2.addWidget(self.open2)
        self.open3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.open3.setObjectName("open3")
        self.verticalLayout_2.addWidget(self.open3)
        self.open4 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.open4.setObjectName("open4")
        self.verticalLayout_2.addWidget(self.open4)
        self.open5 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.open5.setObjectName("open5")
        self.verticalLayout_2.addWidget(self.open5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Недавние"))
        self.open1.setText(_translate("MainWindow", "Открыть"))
        self.open2.setText(_translate("MainWindow", "Открыть"))
        self.open3.setText(_translate("MainWindow", "Открыть"))
        self.open4.setText(_translate("MainWindow", "Открыть"))
        self.open5.setText(_translate("MainWindow", "Открыть"))
