# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '12.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(253, 256)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color : rgb(221, 223, 237)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 160, 170))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.begin = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.begin.setObjectName("begin")
        self.verticalLayout.addWidget(self.begin)
        self.pbcontinue = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbcontinue.setObjectName("pbcontinue")
        self.verticalLayout.addWidget(self.pbcontinue)
        self.pbhistory = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbhistory.setObjectName("pbhistory")
        self.verticalLayout.addWidget(self.pbhistory)
        self.settings = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.settings.setObjectName("settings")
        self.verticalLayout.addWidget(self.settings)
        self.changepbcolor = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.changepbcolor.setFont(font)
        self.changepbcolor.setObjectName("changepbcolor")
        self.verticalLayout.addWidget(self.changepbcolor)
        self.pbreset = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbreset.setObjectName("pbreset")
        self.verticalLayout.addWidget(self.pbreset)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 253, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Меню"))
        self.begin.setText(_translate("MainWindow", "Начать работу"))
        self.pbcontinue.setText(_translate("MainWindow", "Продолжить"))
        self.pbhistory.setText(_translate("MainWindow", "История"))
        self.settings.setText(_translate("MainWindow", "Выбрать цвет фона"))
        self.changepbcolor.setText(_translate("MainWindow", "Выбрать цвет кнопок"))
        self.pbreset.setText(_translate("MainWindow", "Сбросить цвета"))
